version: "3.2"
services:
  web-auth:
    image: jedrula/jedrula-jwt-auth
    ports:
      - "4000:4000"
  fastboot:
    image: jedrula/jedrula-fastboot
    ports:
      - "5000:5000"
  web:
    image: jedrula/jedrula-nodejs-backend
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ~/data/db:/data/db
